const ROLES = {
    SUPERADMIN: 'SUPERADMIN',
    ADMIN: "ADMIN",
    EMPLOYEE: "EMPLOYEE",
    STUDENT: "STUDENT",
};

const FEETYPE = {
    ADMISSION: 'ADMISSION',
    TUITIONFEES: 'TUITIONFEES',
    OTHER: 'OTHER',
};

const PAYMENT_MODE = {
    CASH: 'CASH',
    BANK: 'BANK',
    ONLINE: 'ONLINE',
    CHEQUE: 'CHEQUE',
    OTHER: 'OTHER',
};

const PAYMENT_STATUS = {
    PAID: 'PAID',
    UNPAID: 'UNPAID',
    PENDING: 'PENDING',
    CANECELLED: 'CANECELLED',
};

const COMPLAIN_STATUS = {
    OPEN: 'OPEN',
    IN_PROGRESS: 'IN_PROGRESS',
    RESOLVED: 'RESOLVED',
    REJECTED: 'REJECTED',
};

const COMPLAIN_TYPES = {
    STUDENT: 'STUDENT',
    EMPLOYEE: 'EMPLOYEE',
    PARENTS: 'PARENTS',
    OTHER: 'OTHER',
};

const EXAM_TYPE = {
    UNIT_TEST: 'UNIT_TEST',
    MID_TERM: 'MID_TERM',
    FINAL: 'FINAL',
    PRACTICAL: 'PRACTICAL',
    WEEKLY_TEST: 'WEEKLY_TEST',
    MONTHLY_TEST: 'MONTHLY_TEST',
    ORAL: 'ORAL',
    MOCK: 'MOCK',
    OTHER: 'OTHER',
};

const ATTENDANCE_STATUS = {
    PRESENT: 'PRESENT',
    ABSENT: 'ABSENT',
    LEAVE: 'LEAVE',
    LATE: 'LATE',
};

const EVENT_TYPES = {
    HOLIDAY: "HOLIDAY",
    STUDENT_LEAVE: "STUDENT_LEAVE",
    EMPLOYEE_LEAVE: "EMPLOYEE_LEAVE",
    NOTICE: "NOTICE",
    TEST: "TEST",
    FEE_REMINDER: "FEE_REMINDER",
};

const LEAVE_STATUS = {
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
};

module.exports = {
    ROLES,
    FEETYPE,
    PAYMENT_MODE,
    PAYMENT_STATUS,
    COMPLAIN_STATUS,
    COMPLAIN_TYPES,
    EXAM_TYPE,
    ATTENDANCE_STATUS,
    EVENT_TYPES,
    LEAVE_STATUS,
};
